const mysql = require('mysql2/promise');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');

const INSTALLED_FLAG = path.join(__dirname, '../..', '.installed');
const ENV_FILE = path.join(__dirname, '../..', '.env');
const SCHEMA_FILE = path.join(__dirname, '../..', 'initial_setup.sql');

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Create a raw mysql2 connection using provided config
 */
const createConnection = async (config, useDb = false) => {
  return mysql.createConnection({
    host: config.db_host,
    port: parseInt(config.db_port, 10) || 3306,
    user: config.db_user,
    password: config.db_password,
    ...(useDb ? { database: config.db_name } : {}),
    multipleStatements: true,
    charset: 'utf8mb4',
  });
};

/**
 * Split SQL file into logical phases, stripping comments
 */
const parseSqlPhases = (sql) => {
  // Remove single-line comments, keep structure
  const clean = sql
    .split('\n')
    .filter(line => !line.trim().startsWith('--'))
    .join('\n');

  // Split on semicolon, filter empty
  const statements = clean
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0);

  // Phase 1: CREATE DATABASE + USE — skip (we handle DB creation separately)
  // Phase 2: CREATE TABLE + ALTER TABLE
  // Phase 3: Base seeds — languages, currencies only
  // Phase 4: Skip default company, roles, modules, permissions, users, role_permissions — wizard handles these
  // Phase 5: FK constraints
  // Translation keys/translations — wizard handles these after company creation

  const schema = [];
  const baseSeeds = [];
  const fkConstraints = [];

  const skipPatterns = [
    /^CREATE\s+DATABASE/i,
    /^USE\s+/i,
    /^INSERT\s+INTO\s+`?(companies)/i,
    /^INSERT\s+INTO\s+`?(roles)/i,
    /^INSERT\s+INTO\s+`?(modules)/i,
    /^INSERT\s+INTO\s+`?(permissions)/i,
    /^INSERT\s+INTO\s+`?(users)/i,
    /^INSERT\s+INTO\s+`?(role_permissions)/i,
    /^INSERT\s+INTO\s+`?(settings)/i,
    /^INSERT\s+INTO\s+`?(translation_keys)/i,
    /^INSERT\s+INTO\s+`?(translations)/i,
    /^SET\s+@pwd/i,
    /^SET\s+SQL_SAFE_UPDATES/i,
    /^UPDATE\s+`?roles/i,
    /^UPDATE\s+`?permissions/i,
    /^UPDATE\s+`?translation_keys/i,
    /^SELECT\s+'/i,
  ];

  for (const stmt of statements) {
    const upper = stmt.trim().toUpperCase();

    // Skip unwanted statements
    if (skipPatterns.some(p => p.test(stmt.trim()))) continue;

    if (/^ALTER\s+TABLE/i.test(stmt)) {
      fkConstraints.push(stmt);
    } else if (/^INSERT\s+INTO\s+`?(languages|currencies)/i.test(stmt)) {
      baseSeeds.push(stmt);
    } else if (/^CREATE\s+TABLE/i.test(stmt)) {
      schema.push(stmt);
    }
  }

  return { schema, baseSeeds, fkConstraints };
};

// ─── Exported Service Methods ─────────────────────────────────────────────────

/**
 * Test a MySQL connection with the provided credentials
 */
const testConnection = async (config) => {
  let conn;
  try {
    conn = await createConnection(config, false);
    await conn.query('SELECT 1');
    return { success: true, message: 'Connection successful' };
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Write the .env file with all required variables.
 * Secrets are auto-generated server-side — never sent to frontend.
 */
const writeEnvFile = (config) => {
  const accessSecret = crypto.randomBytes(32).toString('hex');
  const refreshSecret = crypto.randomBytes(32).toString('hex');
  const sessionSecret = crypto.randomBytes(32).toString('hex');

  const envContent = `# =============================================================================
# Generated by Install Wizard — ${new Date().toISOString()}
# =============================================================================

# Server
NODE_ENV=production
PORT=5000

# Database
DB_HOST=${config.db_host || 'localhost'}
DB_PORT=${config.db_port || 3306}
DB_NAME=${config.db_name || 'admin'}
DB_USER=${config.db_user || 'root'}
DB_PASSWORD=${config.db_password || ''}

# JWT Secrets (auto-generated)
ACCESS_TOKEN_SECRET=${accessSecret}
REFRESH_TOKEN_SECRET=${refreshSecret}
SESSION_SECRET=${sessionSecret}

# Token Expiry
ACCESS_TOKEN_EXPIRY=15m
REFRESH_TOKEN_EXPIRY=7d

# CORS / Frontend Domain
CORS_ORIGIN=${config.domain || 'http://localhost:3000'}

# File Uploads
UPLOAD_PATH=${config.upload_path || 'uploads'}
MAX_FILE_SIZE=${config.max_file_size || 5242880}
`;

  fs.writeFileSync(ENV_FILE, envContent, 'utf8');

  // Reload .env into process.env so JWT secrets are available for finalize step
  require('dotenv').config({ path: ENV_FILE, override: true });
};

/**
 * Create the database if it does not already exist
 */
const createDatabase = async (config) => {
  let conn;
  try {
    conn = await createConnection(config, false);
    await conn.query(
      `CREATE DATABASE IF NOT EXISTS \`${config.db_name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`
    );
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Run the schema SQL — creates all tables and inserts base seeds (language + currency).
 * Skips company/role/user/permission data — the wizard handles those dynamically.
 */
const runSchema = async (config) => {
  const rawSql = fs.readFileSync(SCHEMA_FILE, 'utf8');
  const { schema, baseSeeds, fkConstraints } = parseSqlPhases(rawSql);

  let conn;
  try {
    conn = await createConnection(config, true);

    // 1. Create tables
    for (const stmt of schema) {
      await conn.query(stmt);
    }

    // 2. Base seeds (language en, currency USD)
    for (const stmt of baseSeeds) {
      await conn.query(stmt);
    }

    // 3. FK constraints (may fail if already exist — ignore)
    for (const stmt of fkConstraints) {
      try {
        await conn.query(stmt);
      } catch (err) {
        if (err.code !== 'ER_DUP_KEY' && !err.message.includes('Duplicate')) {
          // Ignore duplicate FK errors on re-runs, rethrow others
          if (err.errno !== 1826 && err.errno !== 1025) throw err;
        }
      }
    }
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Create company + modules + permissions + settings scoped to that company.
 * Returns the new company's id.
 */
const createCompany = async (data, config) => {
  let conn;
  try {
    conn = await createConnection(config, true);

    // ── Insert company ──────────────────────────────────────────────────────
    const companySettings = JSON.stringify({
      timezone: data.timezone || 'UTC',
      language: data.language || 'en',
      currency: data.currency || 'USD',
      copyright: data.copyright || data.name,
    });

    const [companyResult] = await conn.query(
      `INSERT INTO \`companies\`
        (name, slug, email, phone, logo, settings, is_active, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, 1, NOW(), NOW())`,
      [
        data.name,
        data.slug,
        data.email || null,
        data.phone || null,
        data.logo || null,
        companySettings,
      ]
    );

    const companyId = companyResult.insertId;

    // ── Insert modules scoped to company ────────────────────────────────────
    const modules = [
      ['Employees', 'employees', 'User/employee management'],
      ['Roles', 'roles', 'Role management'],
      ['Permissions', 'permissions', 'Permission management'],
      ['Modules', 'modules', 'Module management'],
      ['Settings', 'settings', 'Application settings'],
      ['Locations', 'locations', 'Country, state, city management'],
      ['Languages', 'languages', 'Language management'],
      ['Currencies', 'currencies', 'Currency management'],
      ['Media', 'media', 'File upload and management'],
      ['Translations', 'translations', 'Translation key management'],
      ['Email Configs', 'email_configs', 'Email provider configuration'],
      ['Email Templates', 'email_templates', 'Email template management'],
      ['Email Campaigns', 'email_campaigns', 'Email campaign management'],
      ['Activity Logs', 'activity_logs', 'User activity audit logs'],
      ['Approvals', 'approvals', 'Approval workflow management'],
      ['Companies', 'companies', 'Company management (developer only)'],
      ['Pages', 'pages', 'Static page management'],
      ['Blog', 'blog', 'Blog post management'],
      ['Testimonials', 'testimonials', 'Testimonial management'],
      ['Ads', 'ads', 'Advertisement management'],
      ['Announcements', 'announcements', 'Announcement management'],
      ['FAQs', 'faqs', 'FAQ management'],
      ['Contact', 'contact', 'Contact message management'],
      ['Plugins', 'plugins', 'Plugin management'],
      ['Tools', 'tools', 'Admin tools'],
      ['Appearance', 'appearance', 'Theme and appearance settings'],
      ['Platform', 'platform', 'Platform administration'],
    ];

    for (const [name, slug, description] of modules) {
      await conn.query(
        `INSERT INTO \`modules\` (name, slug, description, company_id, is_active, created_at, updated_at)
         VALUES (?, ?, ?, ?, 1, NOW(), NOW())
         ON DUPLICATE KEY UPDATE company_id = VALUES(company_id), is_active = 1`,
        [name, slug, description, companyId]
      );
    }

    // ── Insert permissions scoped to company ─────────────────────────────────
    const permissions = [
      // Employees
      ['View Employees', 'employees.view', 'employees', 'View employee list and details'],
      ['Create Employee', 'employees.create', 'employees', 'Create new employees'],
      ['Edit Employee', 'employees.edit', 'employees', 'Edit employee information'],
      ['Delete Employee', 'employees.delete', 'employees', 'Delete employees'],
      // Roles
      ['View Roles', 'roles.view', 'roles', 'View roles list'],
      ['Manage Roles', 'roles.manage', 'roles', 'Create, edit and delete roles'],
      // Permissions
      ['View Permissions', 'permissions.view', 'permissions', 'View permissions list'],
      ['Manage Permissions', 'permissions.manage', 'permissions', 'Create and edit permissions'],
      // Modules
      ['View Modules', 'modules.view', 'modules', 'View modules list'],
      ['Manage Modules', 'modules.manage', 'modules', 'Create and edit modules'],
      // Settings
      ['View Settings', 'settings.view', 'settings', 'View application settings'],
      ['Edit Settings', 'settings.edit', 'settings', 'Modify application settings'],
      // Locations
      ['View Locations', 'locations.view', 'locations', 'View countries, states, cities'],
      ['Manage Locations', 'locations.manage', 'locations', 'Manage countries, states, cities'],
      // Languages
      ['View Languages', 'languages.view', 'languages', 'View languages list'],
      ['Create Language', 'languages.create', 'languages', 'Add new languages'],
      ['Edit Language', 'languages.edit', 'languages', 'Edit languages'],
      ['Delete Language', 'languages.delete', 'languages', 'Delete languages'],
      // Currencies
      ['View Currencies', 'currencies.view', 'currencies', 'View currencies list'],
      ['Create Currency', 'currencies.create', 'currencies', 'Add new currencies'],
      ['Edit Currency', 'currencies.edit', 'currencies', 'Edit currencies'],
      ['Delete Currency', 'currencies.delete', 'currencies', 'Delete currencies'],
      // Media
      ['View Media', 'media.view', 'media', 'View media library'],
      ['Upload Media', 'media.upload', 'media', 'Upload files'],
      ['Delete Media', 'media.delete', 'media', 'Delete uploaded files'],
      // Translations
      ['View Translations', 'translations.view', 'translations', 'View translation keys'],
      ['Create Translation', 'translations.create', 'translations', 'Create translation keys'],
      ['Edit Translation', 'translations.edit', 'translations', 'Edit translations'],
      ['Delete Translation', 'translations.delete', 'translations', 'Delete translation keys'],
      ['Manage Translations', 'translations.manage', 'translations', 'Manage translation settings'],
      // Email Configs
      ['View Email Configs', 'email_configs.view', 'email_configs', 'View email configurations'],
      ['Create Email Config', 'email_configs.create', 'email_configs', 'Create email configs'],
      ['Edit Email Config', 'email_configs.edit', 'email_configs', 'Edit email configurations'],
      ['Delete Email Config', 'email_configs.delete', 'email_configs', 'Delete email configs'],
      ['Manage Email Configs', 'email_configs.manage', 'email_configs', 'Manage email config settings'],
      // Email Templates
      ['Read Email Templates', 'email_templates.read', 'email_templates', 'View email templates'],
      ['Create Email Template', 'email_templates.create', 'email_templates', 'Create email templates'],
      ['Update Email Template', 'email_templates.update', 'email_templates', 'Update email templates'],
      ['Delete Email Template', 'email_templates.delete', 'email_templates', 'Delete email templates'],
      ['Manage Email Templates', 'email_templates.manage', 'email_templates', 'Manage email templates'],
      // Email Campaigns
      ['Read Email Campaigns', 'email_campaigns.read', 'email_campaigns', 'View email campaigns'],
      ['Create Email Campaign', 'email_campaigns.create', 'email_campaigns', 'Create email campaigns'],
      ['Update Email Campaign', 'email_campaigns.update', 'email_campaigns', 'Update email campaigns'],
      ['Delete Email Campaign', 'email_campaigns.delete', 'email_campaigns', 'Delete email campaigns'],
      ['Manage Email Campaigns', 'email_campaigns.manage', 'email_campaigns', 'Manage campaign actions'],
      // Activity Logs
      ['View Activity Logs', 'activity_logs.view', 'activity_logs', 'View activity logs'],
      ['Delete Activity Logs', 'activity_logs.delete', 'activity_logs', 'Clear activity logs'],
      // Pages
      ['View Pages', 'pages.view', 'pages', 'View pages list'],
      ['Create Page', 'pages.create', 'pages', 'Create pages'],
      ['Edit Page', 'pages.edit', 'pages', 'Edit pages'],
      ['Delete Page', 'pages.delete', 'pages', 'Delete pages'],
      // Blog
      ['View Blog', 'blog.view', 'blog', 'View blog posts'],
      ['Create Blog', 'blog.create', 'blog', 'Create blog posts'],
      ['Edit Blog', 'blog.edit', 'blog', 'Edit blog posts'],
      ['Delete Blog', 'blog.delete', 'blog', 'Delete blog posts'],
      // Testimonials
      ['View Testimonials', 'testimonials.view', 'testimonials', 'View testimonials'],
      ['Create Testimonial', 'testimonials.create', 'testimonials', 'Create testimonials'],
      ['Edit Testimonial', 'testimonials.edit', 'testimonials', 'Edit testimonials'],
      ['Delete Testimonial', 'testimonials.delete', 'testimonials', 'Delete testimonials'],
      // Ads
      ['View Ads', 'ads.view', 'ads', 'View ads'],
      ['Create Ad', 'ads.create', 'ads', 'Create ads'],
      ['Edit Ad', 'ads.edit', 'ads', 'Edit ads'],
      ['Delete Ad', 'ads.delete', 'ads', 'Delete ads'],
      // Announcements
      ['View Announcements', 'announcements.view', 'announcements', 'View announcements'],
      ['Create Announcement', 'announcements.create', 'announcements', 'Create announcements'],
      ['Edit Announcement', 'announcements.edit', 'announcements', 'Edit announcements'],
      ['Delete Announcement', 'announcements.delete', 'announcements', 'Delete announcements'],
      // FAQs
      ['View FAQs', 'faqs.view', 'faqs', 'View FAQs'],
      ['Create FAQ', 'faqs.create', 'faqs', 'Create FAQs'],
      ['Edit FAQ', 'faqs.edit', 'faqs', 'Edit FAQs'],
      ['Delete FAQ', 'faqs.delete', 'faqs', 'Delete FAQs'],
      // Contact
      ['View Contact', 'contact.view', 'contact', 'View contact messages'],
      ['Delete Contact', 'contact.delete', 'contact', 'Delete contact messages'],
      // Plugins
      ['View Plugins', 'plugins.view', 'plugins', 'View plugins'],
      ['Manage Plugins', 'plugins.manage', 'plugins', 'Manage plugins'],
      // Tools
      ['View Tools', 'tools.view', 'tools', 'View admin tools'],
      ['Manage Tools', 'tools.manage', 'tools', 'Use admin tools'],
      // Appearance
      ['View Appearance', 'appearance.view', 'appearance', 'View appearance settings'],
      ['Manage Appearance', 'appearance.manage', 'appearance', 'Manage theme and menus'],
      // Platform
      ['View Platform', 'platform.view', 'platform', 'View platform settings'],
      ['Manage Platform', 'platform.manage', 'platform', 'Manage platform settings'],
    ];

    for (const [name, slug, module, description] of permissions) {
      await conn.query(
        `INSERT INTO \`permissions\` (name, slug, module, company_id, description, is_active, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, 1, NOW(), NOW())
         ON DUPLICATE KEY UPDATE company_id = VALUES(company_id), is_active = 1`,
        [name, slug, module, companyId, description]
      );
    }

    // ── Link permissions to modules via module_id ────────────────────────────
    await conn.query(
      `UPDATE \`permissions\` p
       JOIN \`modules\` m ON m.slug = p.module AND m.company_id = ?
       SET p.module_id = m.id
       WHERE p.company_id = ? AND p.module_id IS NULL`,
      [companyId, companyId]
    );

    // ── Insert default settings scoped to company ────────────────────────────
    const settings = [
      // General settings
      ['site_name', data.name, 'general', 'text', 'Application name'],
      ['site_email', data.email || 'admin@example.com', 'general', 'text', 'Site contact email'],
      ['site_url', config.domain || 'http://localhost:3000', 'general', 'text', 'Frontend URL'],
      ['maintenance_mode', '0', 'general', 'boolean', 'Maintenance mode toggle'],
      ['allow_signup', '1', 'general', 'boolean', 'Allow new registrations'],
      ['default_timezone', data.timezone || 'UTC', 'general', 'text', 'Default timezone'],
      ['default_language', data.language || 'en', 'general', 'text', 'Default language code'],
      ['default_currency', data.currency || 'USD', 'general', 'text', 'Default currency code'],
      ['items_per_page', '25', 'pagination', 'number', 'Default pagination size'],
      ['max_file_size', String(Math.round(parseInt(config.max_file_size || 10485760, 10) / (1024 * 1024))), 'upload', 'number', 'Max upload size (MB)'],
      // Appearance settings (admin settings page reads these)
      ['site_logo_url', data.logo || '', 'appearance', 'text', 'Main site logo URL'],
      ['admin_logo_url', data.logo || '', 'appearance', 'text', 'Admin sidebar logo URL'],
      ['admin_favicon_url', data.favicon || '', 'appearance', 'text', 'Browser tab favicon URL'],
      ['admin_title', 'Admin Panel', 'appearance', 'text', 'Admin panel browser tab title'],
      ['copyright_text', data.copyright || `© ${new Date().getFullYear()} ${data.name}. All rights reserved.`, 'appearance', 'text', 'Footer copyright text'],
      ['admin_email', data.email || 'admin@example.com', 'appearance', 'text', 'Primary admin notification email'],
      ['primary_font', 'inter', 'appearance', 'text', 'Admin panel font family'],
      ['login_background_url', '', 'appearance', 'text', 'Login page background image URL'],
    ];

    for (const [key, value, group, type, description] of settings) {
      await conn.query(
        `INSERT INTO \`settings\` (\`key\`, value, \`group\`, type, description, company_id, is_active, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, 1, NOW(), NOW())
         ON DUPLICATE KEY UPDATE value = VALUES(value), company_id = VALUES(company_id)`,
        [key, value, group, type, description, companyId]
      );
    }

    return companyId;
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Create the super admin user.
 * Also creates: Developer role (level 1000, no company) + Super Admin role (level 100).
 * Returns the created user object (without password).
 */
const createAdmin = async (data, companyId, config) => {
  let conn;
  try {
    conn = await createConnection(config, true);

    // ── Developer role (global — no company_id) ──────────────────────────────
    const [devRoleResult] = await conn.query(
      `INSERT INTO \`roles\` (name, slug, description, level, company_id, is_default, is_active, created_at, updated_at)
       VALUES ('Developer', 'developer', 'Full system access across all companies. Bypasses all checks.', 1000, NULL, 0, 1, NOW(), NOW())
       ON DUPLICATE KEY UPDATE level = 1000, is_active = 1`,
    );
    // Get developer role id (insert or existing)
    const [[devRole]] = await conn.query(
      `SELECT id FROM \`roles\` WHERE slug = 'developer' AND company_id IS NULL LIMIT 1`
    );
    const developerRoleId = devRole.id;

    // Update created_by on developer role to itself (convention)
    await conn.query(
      `UPDATE \`roles\` SET created_by = ? WHERE id = ? AND created_by IS NULL`,
      [developerRoleId, developerRoleId]
    );

    // ── Super Admin role (scoped to company) ─────────────────────────────────
    await conn.query(
      `INSERT INTO \`roles\` (name, slug, description, level, company_id, is_default, is_active, created_by, created_at, updated_at)
       VALUES ('Super Admin', 'super_admin', 'Full administrative access. Approves pending requests.', 100, ?, 0, 1, ?, NOW(), NOW())
       ON DUPLICATE KEY UPDATE level = 100, is_active = 1, company_id = VALUES(company_id)`,
      [companyId, developerRoleId]
    );

    const [[superAdminRole]] = await conn.query(
      `SELECT id FROM \`roles\` WHERE slug = 'super_admin' AND company_id = ? LIMIT 1`,
      [companyId]
    );
    const superAdminRoleId = superAdminRole.id;

    // ── Hash password ─────────────────────────────────────────────────────────
    const hashedPassword = await bcrypt.hash(data.password, 12);

    // ── Create super admin user ───────────────────────────────────────────────
    const [userResult] = await conn.query(
      `INSERT INTO \`users\`
        (full_name, email, password, role_id, company_id, avatar, login_access, email_verified_at, is_active, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, 1, NOW(), 1, NOW(), NOW())`,
      [
        data.full_name,
        data.email,
        hashedPassword,
        superAdminRoleId,
        companyId,
        data.avatar || null,
      ]
    );

    const userId = userResult.insertId;

    // Update roles created_by to super admin user
    await conn.query(
      `UPDATE \`roles\` SET created_by = ? WHERE company_id = ? AND created_by IS NULL`,
      [userId, companyId]
    );

    // Update company created_by
    await conn.query(
      `UPDATE \`companies\` SET created_by = ? WHERE id = ?`,
      [userId, companyId]
    );

    // Update permissions + modules created_by
    await conn.query(
      `UPDATE \`permissions\` SET created_by = ? WHERE company_id = ? AND created_by IS NULL`,
      [userId, companyId]
    );
    await conn.query(
      `UPDATE \`modules\` SET created_by = ? WHERE company_id = ? AND created_by IS NULL`,
      [userId, companyId]
    );

    // ── Assign ALL permissions to Super Admin role ────────────────────────────
    await conn.query(
      `INSERT INTO \`role_permissions\` (role_id, permission_id, created_at, updated_at)
       SELECT ?, id, NOW(), NOW()
       FROM \`permissions\`
       WHERE company_id = ?
       ON DUPLICATE KEY UPDATE updated_at = NOW()`,
      [superAdminRoleId, companyId]
    );

    return {
      id: userId,
      full_name: data.full_name,
      email: data.email,
      role_id: superAdminRoleId,
      company_id: companyId,
    };
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Insert all translation keys + English translations scoped to the company.
 * Mirrors the SQL seed from initial_setup.sql but with dynamic company_id.
 */
const seedTranslations = async (companyId, config) => {
  // Re-read the SQL file and extract translation_keys insert statements
  // We'll reproduce the full set programmatically to avoid parsing complexity
  const translationKeys = [
    // nav
    ['nav.navigation', 'Navigation', 'nav'],
    ['nav.dashboard', 'Dashboard', 'nav'],
    ['nav.companies', 'Companies', 'nav'],
    ['nav.approvals', 'Approvals', 'nav'],
    ['nav.employees', 'Employees', 'nav'],
    ['nav.pages', 'Pages', 'nav'],
    ['nav.blog', 'Blog', 'nav'],
    ['nav.testimonials', 'Testimonials', 'nav'],
    ['nav.ads', 'Ads', 'nav'],
    ['nav.announcements', 'Announcements', 'nav'],
    ['nav.faqs', 'FAQs', 'nav'],
    ['nav.faq_list', 'FAQ List', 'nav'],
    ['nav.faq_categories', 'FAQ Categories', 'nav'],
    ['nav.locations', 'Locations', 'nav'],
    ['nav.contact', 'Contact', 'nav'],
    ['nav.media', 'Media', 'nav'],
    ['nav.plugins', 'Plugins', 'nav'],
    ['nav.payments', 'Payments', 'nav'],
    ['nav.tools', 'Tools', 'nav'],
    ['nav.access_control', 'Access Control', 'nav'],
    ['nav.roles', 'Roles', 'nav'],
    ['nav.modules', 'Modules', 'nav'],
    ['nav.appearance', 'Appearance', 'nav'],
    ['nav.theme', 'Theme', 'nav'],
    ['nav.menu', 'Menu', 'nav'],
    ['nav.theme_option', 'Theme Options', 'nav'],
    ['nav.settings', 'Settings', 'nav'],
    ['nav.platform_admin', 'Platform Admin', 'nav'],
    ['nav.profile', 'Profile', 'nav'],
    ['nav.translations', 'Translations', 'nav'],
    ['nav.activity_logs', 'Activity Logs', 'nav'],
    ['nav.currencies', 'Currencies', 'nav'],
    ['nav.email_templates', 'Email Templates', 'nav'],
    ['nav.languages', 'Languages', 'nav'],
    ['nav.missing_keys', 'Missing Keys', 'nav'],
    ['nav.modules', 'Modules', 'nav'],
    ['nav.permissions', 'Permissions', 'nav'],
    ['nav.platform', 'Platform', 'nav'],
    ['nav.configuration', 'Configuration', 'nav'],
    // common
    ['common.name', 'Name', 'common'],
    ['common.description', 'Description', 'common'],
    ['common.status', 'Status', 'common'],
    ['common.actions', 'Actions', 'common'],
    ['common.action', 'Action', 'common'],
    ['common.active', 'Active', 'common'],
    ['common.inactive', 'Inactive', 'common'],
    ['common.approved', 'Approved', 'common'],
    ['common.create', 'Create', 'common'],
    ['common.edit', 'Edit', 'common'],
    ['common.delete', 'Delete', 'common'],
    ['common.save', 'Save', 'common'],
    ['common.saving', 'Saving...', 'common'],
    ['common.cancel', 'Cancel', 'common'],
    ['common.submit', 'Submit', 'common'],
    ['common.loading', 'Loading...', 'common'],
    ['common.deleting', 'Deleting...', 'common'],
    ['common.changing', 'Changing...', 'common'],
    ['common.code', 'Code', 'common'],
    ['common.email', 'Email', 'common'],
    ['common.user', 'User', 'common'],
    ['common.date', 'Date', 'common'],
    ['common.page', 'Page', 'common'],
    ['common.next', 'Next', 'common'],
    ['common.previous', 'Previous', 'common'],
    ['common.optional', 'Optional', 'common'],
    ['common.comming', 'Coming Soon', 'common'],
    // settings
    ['settings.page_desc', 'Manage your application settings', 'settings'],
    ['settings.general', 'General', 'settings'],
    ['settings.general_desc', 'Basic site configuration', 'settings'],
    ['settings.email', 'Email', 'settings'],
    ['settings.email_desc', 'Email provider settings', 'settings'],
    ['settings.email_templates', 'Email Templates', 'settings'],
    ['settings.email_templates_desc', 'Manage email templates', 'settings'],
    ['settings.email_campaigns', 'Email Campaigns', 'settings'],
    ['settings.email_campaigns_desc', 'Manage email campaigns', 'settings'],
    ['settings.languages', 'Languages', 'settings'],
    ['settings.languages_desc', 'Manage supported languages', 'settings'],
    ['settings.currencies', 'Currencies', 'settings'],
    ['settings.currencies_desc', 'Manage supported currencies', 'settings'],
    ['settings.media', 'Media', 'settings'],
    ['settings.media_desc', 'File upload settings', 'settings'],
    ['settings.translations', 'Translations', 'settings'],
    ['settings.translations_desc', 'Manage translation keys', 'settings'],
    ['settings.locations', 'Locations', 'settings'],
    ['settings.locations_desc', 'Manage countries, states and cities', 'settings'],
    ['settings.timezone', 'Timezone', 'settings'],
    ['settings.timezone_desc', 'Configure application timezone', 'settings'],
    ['settings.site_settings', 'Site Settings', 'settings'],
    ['settings.site_settings_desc', 'Configure site-wide settings', 'settings'],
    ['settings.social_login', 'Social Login', 'settings'],
    ['settings.social_login_desc', 'Configure social authentication', 'settings'],
    ['settings.website_tracking', 'Website Tracking', 'settings'],
    ['settings.website_tracking_desc', 'Configure analytics tracking', 'settings'],
    ['settings.dashboard_theme', 'Dashboard Theme', 'settings'],
    ['settings.dashboard_theme_desc', 'Customize dashboard appearance', 'settings'],
    ['settings.phone_number', 'Phone Number', 'settings'],
    ['settings.phone_number_desc', 'Configure phone number settings', 'settings'],
    ['settings.cache', 'Cache', 'settings'],
    ['settings.cache_desc', 'Manage cache settings', 'settings'],
    ['settings.common', 'Common', 'settings'],
    ['settings.localization', 'Localization', 'settings'],
    ['settings.optimize', 'Optimize', 'settings'],
    ['settings.optimize_desc', 'Performance optimization', 'settings'],
    ['settings.optimize_settings_view', 'Optimization Settings', 'settings'],
    ['settings.performance', 'Performance', 'settings'],
    // dashboard
    ['dashboard.welcome_admin', 'Welcome back, Admin', 'dashboard'],
    ['dashboard.quick_actions', 'Quick Actions', 'dashboard'],
    ['dashboard.total_users', 'Total Users', 'dashboard'],
    // auth
    ['auth.greeting', 'Hello', 'auth'],
    ['auth.welcome', 'Welcome', 'auth'],
    ['auth.welcome_back', 'Welcome Back', 'auth'],
    ['auth.logout', 'Logout', 'auth'],
    // profile
    ['profile.title', 'Profile', 'profile'],
    ['profile.description', 'Manage your account', 'profile'],
    ['profile.my_account', 'My Account', 'profile'],
    ['profile.account_details', 'Account Details', 'profile'],
    ['profile.account_info', 'Account Info', 'profile'],
    ['profile.personal_info', 'Personal Information', 'profile'],
    ['profile.personal_info_desc', 'Update your personal info', 'profile'],
    ['profile.full_name', 'Full Name', 'profile'],
    ['profile.phone', 'Phone', 'profile'],
    ['profile.last_login', 'Last Login', 'profile'],
    ['profile.update_profile', 'Update Profile', 'profile'],
    ['profile.change_password', 'Change Password', 'profile'],
    ['profile.change_password_desc', 'Update your password', 'profile'],
    ['profile.current_password', 'Current Password', 'profile'],
    ['profile.new_password', 'New Password', 'profile'],
    ['profile.confirm_new_password', 'Confirm New Password', 'profile'],
    ['profile.confirm_password', 'Confirm Password', 'profile'],
    ['profile.enter_current_password', 'Enter current password', 'profile'],
    ['profile.enter_new_password', 'Enter new password', 'profile'],
    // roles
    ['roles.role', 'Role', 'roles'],
    ['roles.add_role', 'Add Role', 'roles'],
    ['roles.search', 'Search roles...', 'roles'],
    ['roles.no_roles_found', 'No roles found', 'roles'],
    ['roles.edit', 'Edit Role', 'roles'],
    ['roles.manage_roles', 'Manage Roles', 'roles'],
    // languages
    ['languages.title', 'Languages', 'languages'],
    ['languages.add_language', 'Add Language', 'languages'],
    ['languages.add_desc', 'Add a new language', 'languages'],
    ['languages.edit_language', 'Edit Language', 'languages'],
    ['languages.edit_desc', 'Update language details', 'languages'],
    ['languages.native_name', 'Native Name', 'languages'],
    ['languages.direction', 'Direction', 'languages'],
    ['languages.set_default', 'Set as Default', 'languages'],
    ['languages.search', 'Search languages...', 'languages'],
    ['languages.no_languages_found', 'No languages found', 'languages'],
    ['languages.delete_title', 'Delete Language', 'languages'],
    ['languages.translate_all', 'Translate All', 'languages'],
    ['languages.translate_all_title', 'Translate All Keys', 'languages'],
    ['languages.translating', 'Translating...', 'languages'],
    ['languages.translating_title', 'Translating', 'languages'],
    ['languages.translating_to', 'Translating to', 'languages'],
    ['languages.delete_confirm', 'Confirm delete?', 'languages'],
    ['languages.please_wait', 'Please wait...', 'languages'],
    ['languages.translate_all_confirm', 'Translate all keys?', 'languages'],
    ['languages.translating_progress', 'Translation in progress...', 'languages'],
    // currencies
    ['currencies.title', 'Currencies', 'currencies'],
    ['currencies.add_currency', 'Add Currency', 'currencies'],
    ['currencies.add_desc', 'Add a new currency', 'currencies'],
    ['currencies.edit_currency', 'Edit Currency', 'currencies'],
    ['currencies.edit_desc', 'Update currency details', 'currencies'],
    ['currencies.symbol', 'Symbol', 'currencies'],
    ['currencies.exchange_rate', 'Exchange Rate', 'currencies'],
    ['currencies.search', 'Search currencies...', 'currencies'],
    ['currencies.no_currencies_found', 'No currencies found', 'currencies'],
    ['currencies.delete_confirm', 'Confirm Delete', 'currencies'],
    // translations
    ['translations.total_keys', 'Total Keys', 'translations'],
    ['translations.completion_stats', 'Completion Stats', 'translations'],
    ['translations.missing_keys', 'Missing Keys', 'translations'],
    ['translations.missing_keys_desc', 'Keys detected but not translated', 'translations'],
    ['translations.missing_keys_detected', 'Missing keys detected', 'translations'],
    ['translations.add_key', 'Add Key', 'translations'],
    ['translations.add_key_title', 'Add Translation Key', 'translations'],
    ['translations.add_key_desc', 'Create a new translation key', 'translations'],
    ['translations.edit_translations', 'Edit Translations', 'translations'],
    ['translations.key', 'Key', 'translations'],
    ['translations.group', 'Group', 'translations'],
    ['translations.default_value', 'Default Value', 'translations'],
    ['translations.description_placeholder', 'Describe this key...', 'translations'],
    ['translations.key_format', 'Use dot notation: group.key', 'translations'],
    ['translations.languages', 'Languages', 'translations'],
    ['translations.all_languages', 'All Languages', 'translations'],
    ['translations.all_groups', 'All Groups', 'translations'],
    ['translations.all_status', 'All Status', 'translations'],
    ['translations.filter_group', 'Filter by Group', 'translations'],
    ['translations.filter_language', 'Filter by Language', 'translations'],
    ['translations.filter_status', 'Filter by Status', 'translations'],
    ['translations.search_placeholder', 'Search keys...', 'translations'],
    ['translations.select_group', 'Select Group', 'translations'],
    ['translations.new_group', 'New Group', 'translations'],
    ['translations.no_keys_found', 'No translation keys found', 'translations'],
    ['translations.no_keys_with_status', 'No keys with this status', 'translations'],
    ['translations.status_auto', 'Auto', 'translations'],
    ['translations.status_reviewed', 'Reviewed', 'translations'],
    ['translations.status_missing', 'Missing', 'translations'],
    ['translations.auto_translate', 'Auto Translate', 'translations'],
    ['translations.retranslate', 'Re-translate', 'translations'],
    ['translations.english_default', 'English (Default)', 'translations'],
    ['translations.english_original', 'English Original', 'translations'],
    ['translations.translation_in', 'Translation in', 'translations'],
    ['translations.view_resolve', 'View & Resolve', 'translations'],
    ['translations.enter_group_name', 'Enter group name', 'translations'],
    // activity
    ['activity.logs', 'Activity Logs', 'activity'],
    ['activity.logs_desc', 'User activity audit trail', 'activity'],
    ['activity.recent', 'Recent Activity', 'activity'],
    ['activity.no_activity', 'No activity yet', 'activity'],
    ['activity.view_all', 'View All', 'activity'],
    ['activity.date_time', 'Date & Time', 'activity'],
    ['activity.ip_address', 'IP Address', 'activity'],
    // platform
    ['platform.page_desc', 'Manage platform settings', 'platform'],
    ['platform.system', 'System', 'platform'],
    ['platform.employee_management', 'Employee Management', 'platform'],
    ['platform.employees_desc', 'Manage employees and users', 'platform'],
    ['platform.roles_desc', 'Manage roles and permissions', 'platform'],
    ['platform.modules_desc', 'Manage system modules', 'platform'],
    ['platform.activity_desc', 'View user activity logs', 'platform'],
    ['platform.cache_manager', 'Cache Manager', 'platform'],
    ['platform.cache_desc', 'Manage application cache', 'platform'],
    ['platform.profile_desc', 'Manage your profile', 'platform'],
    // appearance
    ['appearance.menu', 'Menu', 'appearance'],
    ['appearance.theme', 'Theme', 'appearance'],
    ['appearance.theme_options', 'Theme Options', 'appearance'],
  ];

  let conn;
  try {
    conn = await createConnection(config, true);

    // Get English language id
    const [[enLang]] = await conn.query(
      `SELECT id FROM \`languages\` WHERE code = 'en' LIMIT 1`
    );
    const languageId = enLang ? enLang.id : 1;

    for (const [key, defaultValue, group] of translationKeys) {
      // Insert translation key (NO company_id — translations are global/system-level)
      await conn.query(
        `INSERT INTO \`translation_keys\` (\`key\`, default_value, \`group\`, created_at, updated_at)
         VALUES (?, ?, ?, NOW(), NOW())
         ON DUPLICATE KEY UPDATE default_value = VALUES(default_value)`,
        [key, defaultValue, group]
      );

      // Get the key id
      const [[tkRow]] = await conn.query(
        `SELECT id FROM \`translation_keys\` WHERE \`key\` = ? LIMIT 1`,
        [key]
      );

      if (tkRow) {
        // Insert English translation (NO company_id — translations are global)
        await conn.query(
          `INSERT INTO \`translations\` (translation_key_id, language_id, value, status, is_active, created_at, updated_at)
           VALUES (?, ?, ?, 'reviewed', 1, NOW(), NOW())
           ON DUPLICATE KEY UPDATE value = VALUES(value), status = 'reviewed'`,
          [tkRow.id, languageId, defaultValue]
        );
      }
    }
  } finally {
    if (conn) await conn.end();
  }
};

/**
 * Create the .installed marker file to lock the setup routes permanently
 */
const markInstalled = () => {
  fs.writeFileSync(INSTALLED_FLAG, new Date().toISOString(), 'utf8');
};

module.exports = {
  testConnection,
  writeEnvFile,
  createDatabase,
  runSchema,
  createCompany,
  createAdmin,
  seedTranslations,
  markInstalled,
};